### ISSUE TITLE
Update to 1.18.x

### ISSUE THREAD

**Issue by Epikest** [MaheEvil/Where-Is-My-Stuff#1]

**Comment by AdelinaM17n** [comment]
Oh yea I forgot to push the updated build script, sorry I will get on that

**Comment by AdelinaM17n** [comment]
> Oh yea I forgot to push the updated build script, sorry I will get on that

Hmm actually I have seem to updated the build script, are you asking me to update CF or Modrinth releases ? I'll get to that then

**Comment by Epikest** [comment]
> > Oh yea I forgot to push the updated build script, sorry I will get on that
> 
> Hmm actually I have seem to updated the build script, are you asking me to update CF or Modrinth releases ? I'll get to that then

yeah

**Comment by AdelinaM17n** [comment]
Alright updated both in CF and Modrinth

**Comment by Epikest** [comment]
thank you
