### ISSUE TITLE
[1.20.1] [Quilt] [v1.1.2] Mod fails to load on Quilt

### ISSUE THREAD

**Issue by JuceInUse** [MaheEvil/Where-Is-My-Stuff#2]
![image](https://github.com/MaheEvil/Where-Is-My-Stuff/assets/85078618/96112e6f-c6e4-4163-ad21-8f567978750e)

I did a double-check to make sure that this wasn't my bad by just using the mod and the latest version of the Quilt API, and the issue seems to persist

**Comment by AdelinaM17n** [comment]
Fixed in the latest version
